// <auto-generated />
using System;
using BestStoreMVC.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestStoreMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestStoreMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 6, 1, 14, 13, 16, 724, DateTimeKind.Local).AddTicks(7696),
                            Description = "ASUS ROG Zephyrus G14 GA402XZ-NC009W, 14.0, WQXGA, AMD Ryzen 9 7940HS (4.0/5.2GHz, 16M), NVIDIA RTX 4080 12 GB GDDR6 DLSS 3, 32 GB, 1 TB SSD - 90NR0DH6-M000L0",
                            ImageFileName = "asus-ga402-rog-zephyrus-g14-2023-456146.jpg",
                            Name = "ASUS ROG Zephyrus",
                            Price = 3771m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "ASUS",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 6, 1, 14, 13, 16, 724, DateTimeKind.Local).AddTicks(7750),
                            Description = "ASUS ROG Zephyrus G14 GA402XZ-NC009W, 14.0, WQXGA, AMD Ryzen 9 7940HS (4.0/5.2GHz, 16M), NVIDIA RTX 4080 12 GB GDDR6 DLSS 3, 32 GB, 1 TB SSD - 90NR0DH6-M000L0",
                            ImageFileName = "asus-ga402-rog-zephyrus-g14-2023-456146.jpg",
                            Name = "ASUS ROG Zephyrus",
                            Price = 3771m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "ASUS",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 6, 1, 14, 13, 16, 724, DateTimeKind.Local).AddTicks(7752),
                            Description = "ASUS ROG Zephyrus G14 GA402XZ-NC009W, 14.0, WQXGA, AMD Ryzen 9 7940HS (4.0/5.2GHz, 16M), NVIDIA RTX 4080 12 GB GDDR6 DLSS 3, 32 GB, 1 TB SSD - 90NR0DH6-M000L0",
                            ImageFileName = "asus-ga402-rog-zephyrus-g14-2023-456146.jpg",
                            Name = "ASUS ROG Zephyrus",
                            Price = 3771m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
